// <auto-generated />

using DigestsSubDomain.Data.EfCore.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DigestsSubDomain.Data.EfCore.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190118093757_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DigestsSubDomain.Data.Entities.EfCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("DigestsSubDomain.Data.Entities.HouseDigests.EfHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("District");

                    b.Property<string>("Geo");

                    b.Property<string>("MetroStation");

                    b.Property<string>("Number");

                    b.Property<string>("Street");

                    b.Property<int>("WallMaterialId");

                    b.Property<int?>("Year");

                    b.HasKey("Id");

                    b.HasIndex("WallMaterialId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("DigestsSubDomain.Data.Entities.HouseDigests.EfWallMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("WallMaterials");
                });

            modelBuilder.Entity("DigestsSubDomain.Data.Entities.HouseDigests.EfHouse", b =>
                {
                    b.HasOne("DigestsSubDomain.Data.Entities.HouseDigests.EfWallMaterial", "WallMaterial")
                        .WithMany("Houses")
                        .HasForeignKey("WallMaterialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
